# HellaSwag zero-shot evaluation using the text-only path of SmolVLM.
task: hellaswag
model:
  model_id: HuggingFaceTB/SmolVLM-256M-Instruct
  is_vlm: false
  dtype: bfloat16
  device: cuda
  trust_remote_code: true
  attn_impl: flash_attention_2
scoring:
  seed: 123
report:
  output_dir: artifacts/nanoeval/hellaswag/smolvlm-256m
  summary_filename: summary.json
  predictions_filename: predictions.jsonl
  table_filename: metrics.csv
  plot_filename: accuracy.png
  save_predictions: true
  save_table: true
  save_plot: true
dataset:
  split: validation
  subset_size: null
