# MMMU-Pro standard (10 option) evaluation with SmolVLM.
task: mmmu_pro
model:
  model_id: HuggingFaceTB/SmolVLM-256M-Instruct
  is_vlm: true
  dtype: bfloat16
  device: cuda
  trust_remote_code: true
  attn_impl: flash_attention_2
scoring:
  strategy: gen_letter
  max_new_tokens: 8
  seed: 123
report:
  output_dir: artifacts/nanoeval/mmmu_pro/smolvlm-256m
  summary_filename: summary.json
  predictions_filename: predictions.jsonl
  table_filename: metrics.csv
  plot_filename: accuracy.png
  save_predictions: true
  save_table: true
  save_plot: true
dataset:
  subset_name: "standard (10 options)"
  split: test
  subset_size: null
